@startuml Fluxion Component Architecture

!theme crt-amber
left to right direction

title Fluxion - Component Dependency Diagram

package "Graphite Framework" {
    component [Logger] as GLogger
    component [Common\n(TDoubleBuffer, TThreadSafeQueue,\nTWithFlags, UniqueID, Ref)] as GCommon
    component [Application\n(TGraphiteApplication, TView,\nTDispatcher, TSoftCloseableView)] as GApp
    component [Renderer\n(VulkanRenderer, MetalRenderer)] as GRenderer
}

package "API" {
    component [Data\n(Highlight, Condition, Filter,\nLogRow, ColumnDetails)] as APIData
    component [LogsPlugin\n(IFluxionLogsPlugin,\nPluginBridge)] as APIPlugin
}

package "Application" {
    component [Fluxion\n(Main Orchestrator)] as AppFluxion
    component [Data\n(AppState, Tab,\nFiltersGeneralMetadata)] as AppData
    
    package "Views" {
        component [BaseView] as ViewBase
        component [MainMenuView] as ViewMenu
        component [DevView] as ViewDev
        component [FiltersView] as ViewFilters
        component [LogsTableView] as ViewLogs
    }
}

GCommon --> GLogger
GApp --> GLogger
GApp --> GCommon
GApp --> GRenderer
GRenderer --> GLogger
GRenderer --> GCommon

APIData --> GCommon
APIPlugin --> APIData

AppFluxion --> GApp
AppFluxion --> APIPlugin
AppFluxion --> AppData
AppFluxion --> ViewBase
AppFluxion --> ViewMenu
AppFluxion --> ViewDev
AppFluxion --> ViewFilters
AppFluxion --> ViewLogs

AppData --> GCommon
AppData --> GLogger
AppData --> APIData
AppData --> APIPlugin

ViewBase --> GApp
ViewBase --> AppData
ViewBase --> GLogger

ViewMenu --> GApp
ViewMenu --> AppData
ViewMenu --> GLogger

ViewDev --> GApp
ViewDev --> AppData
ViewDev --> GLogger

ViewFilters --> GApp
ViewFilters --> AppData
ViewFilters --> APIData
ViewFilters --> GCommon
ViewFilters --> GLogger

ViewLogs --> GApp
ViewLogs --> AppData
ViewLogs --> APIData
ViewLogs --> APIPlugin
ViewLogs --> GCommon
ViewLogs --> GLogger

@enduml
